os: linux
dist: xenial
language: node_js
node_js:
  - "12"

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

script:
  - npm run build-ci

deploy:
  strategy: git
  provider: pages
  token: $GITHUB_TOKEN
  on:
    branch: master

before_deploy:
  - touch .nojekyll
  - sed -i '/doc/d' .gitignore